# Generated by Django 4.2.5 on 2023-09-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_comment_alter_featurepost_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurepost',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
