# Generated by Django 4.2.5 on 2023-10-01 21:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurepost',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
