# Generated by Django 4.2.5 on 2023-10-03 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_content_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='feature_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.featurepost'),
        ),
    ]
