# Generated by Django 4.2.5 on 2023-09-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='forum-author1.png', upload_to='avatar'),
        ),
    ]
