# Generated by Django 4.2.5 on 2023-09-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_followercount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followercount',
            old_name='iuser',
            new_name='user',
        ),
    ]
