# Generated by Django 4.2.5 on 2023-09-28 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_iuser_followercount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='followercount',
            name='follower_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
